<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bongo\Module'                        => __DIR__ . '/Module.php',
    'Bongo\Controller\SkeletonController' => __DIR__ . '/src/Bongo/Controller/SkeletonController.php',
    'Bongo\Framework\TestCase'        => __DIR__ . '/tests/Bongo/Framework/TestCase.php',
    'Bongo\SampleTest'                => __DIR__ . '/tests/Bongo/SampleTest.php',
);